### PR TITLE
added documentation for watching templates

### PR DESCRIPTION
**Pull request by witmicko**
updated `README` to include info about watch task

### CODE REVIEW

**Comment by wtrocki** [comment]
@witmicko Sorry for this but this option is already there: 
https://github.com/feedhenry-raincatcher/step-template/blob/master/package.json#L8

It seems to be forgotten in README so fix should be to include it.

**Comment by wtrocki** [comment]
https://github.com/feedhenry-raincatcher/step-template/blame/master/README.md#L131

**Comment by witmicko** [comment]
> It seems to be forgotten in README so fix should be to include it.

added info to readme

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
ping @austincunningham README was updated. We need to backport that change into documentation as it's missing this information. 

Edit: it seems that we are ok.

**Pull request merged**
